controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    
    # значение контроллера ммеет формат 'controller_class::method_name'
    controller: App\Controller\HomeController::home

 